server:
  servlet:
    context-path: /kinozen

spring:
  profiles:
    include: 'private'
  datasource:
    url: jdbc:postgresql://localhost:5432/kinozen
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

playerzen:
  service:
    url: "http://localhost:8181/playerzen"
collection:
  service:
    url: "http://localhost:8191/collection-service"

files:
  storage:
    video_download: "D:\\video_download"